name: DVC Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.dvc'
      - '.dvc/**'

jobs:
  run_data_checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: Install dependencies
      run: |
        make dev_requirements
        pip list

    - name: Configure DVC remote with credentials
      run: |
        # Parse the GDRIVE_CREDENTIALS secret
        echo "${{ secrets.GDRIVE_CREDENTIALS }}" > gdrive_credentials.env
        source gdrive_credentials.env

        # Configure DVC remote with parsed credentials
        dvc remote modify myremote gdrive_client_id $gdrive_client_id
        dvc remote modify myremote gdrive_client_secret $gdrive_client_secret

    - name: Pull data
      run: |
        dvc pull --no-run-cache --cloud

    - name: Check data statistics
      run: |
        python dataset_statistics.py
