name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Authenticate with GCP
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" > gcp-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
      env:
        GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json

    - name: Pull DVC Data
      run: |
        dvc pull
        ls data/processed  # Verify the file is present

    - name: Run Tests
      run: pytest -v